import {useEffect,useState} from 'react';import {ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {supabase} from '../lib/supabase';
export default function App(){const [session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[jobs,setJobs]=useState<any[]>([]),[job,setJob]=useState<any>(null),[templates,setTemplates]=useState<any[]>([]),[quote,setQuote]=useState<any>(null),[name,setName]=useState(''),[accepted,setAccepted]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(true);
useEffect(()=>{supabase.auth.getSession().then(x=>{setSession(x.data.session);setBusy(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(session)load()},[session]);
async function load(){setBusy(true);const [{data:j},{data:t}]=await Promise.all([supabase.from('jobs').select('id,request,status,scheduled_start,service_call_required,service_call_completed_at,clients(name,address,phone),technician_id').order('scheduled_start'),supabase.from('scope_templates').select('id,name,trade,description').eq('active',true).order('name')]);setJobs(j||[]);setTemplates(t||[]);setBusy(false)}
async function login(){setMsg('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}
async function start(tid:string){const {error}=await supabase.rpc('start_field_quote',{target_job:job.id,target_template:tid});if(error)return setMsg(error.message);await calc()}
async function calc(){const {data,error}=await supabase.rpc('calculate_field_quote',{target_job:job.id,selected_profile:null});if(error)return setMsg(error.message);setQuote(data)}
async function qty(i:any,d:number){const n=Math.max(0,Number(i.quantity)+d);const {error}=await supabase.rpc('update_field_quote_quantity',{target_item:i.id,new_quantity:n});if(error)return setMsg(error.message);await calc()}
async function approve(){const {error}=await supabase.rpc('finalize_field_quote',{target_job:job.id,typed_name:name,accepted});if(error)return setMsg(error.message);setMsg('Approved · invoice outline created');setQuote(null);await load()}
if(busy)return <SafeAreaView style={s.center}><ActivityIndicator/></SafeAreaView>;
if(!session)return <SafeAreaView style={s.shell}><View style={s.login}><Text style={s.brand}>clarifi</Text><Text style={s.h1}>Technician sign in</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" placeholder="Email" value={email} onChangeText={setEmail}/><TextInput style={s.input} secureTextEntry placeholder="Password" value={password} onChangeText={setPassword}/><Pressable style={s.primary} onPress={login}><Text style={s.primaryText}>Sign in</Text></Pressable>{!!msg&&<Text>{msg}</Text>}</View></SafeAreaView>;
if(!job)return <SafeAreaView style={s.shell}><View style={s.top}><Text style={s.brand}>clarifi</Text><Pressable onPress={()=>supabase.auth.signOut()}><Text>Sign out</Text></Pressable></View><ScrollView contentContainerStyle={s.pad}><Text style={s.eyebrow}>TODAY</Text><Text style={s.h1}>Your jobs</Text>{jobs.map(j=><Pressable key={j.id} style={s.card} onPress={()=>{setJob(j);setQuote(null);setMsg('')}}><Text style={s.cardTitle}>{j.clients?.name||'Client'}</Text><Text>{j.request}</Text><Text style={s.muted}>{j.clients?.address||'Address pending'} · {j.status}</Text></Pressable>)}</ScrollView></SafeAreaView>;
return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.pad}><Pressable onPress={()=>{setJob(null);setQuote(null)}}><Text>‹ Today</Text></Pressable><Text style={s.eyebrow}>SERVICE CALL</Text><Text style={s.h1}>{job.clients?.name}</Text><Text>{job.request}</Text><Text style={s.muted}>{job.clients?.address}</Text>{!quote?<><Text style={s.section}>Select template</Text>{templates.map(t=><Pressable key={t.id} style={s.card} onPress={()=>start(t.id)}><Text style={s.cardTitle}>{t.name}</Text><Text style={s.muted}>{t.description}</Text></Pressable>)}</>:<><Text style={s.section}>Quote</Text>{quote.lines?.map((i:any)=><View key={i.id} style={s.line}><View style={s.grow}><Text style={s.cardTitle}>{i.name}</Text><Text style={s.muted}>{i.unit}</Text></View><View style={s.step}><Pressable onPress={()=>qty(i,-1)}><Text style={s.stepText}>−</Text></Pressable><Text>{i.quantity}</Text><Pressable onPress={()=>qty(i,1)}><Text style={s.stepText}>+</Text></Pressable></View><Text>{'$'}{Number(i.sell_total).toFixed(2)}</Text></View>)}<View style={s.total}><Text>Total</Text><Text style={s.totalN}>{'$'}{Number(quote.total).toFixed(2)}</Text></View><TextInput style={s.input} placeholder="Customer full name" value={name} onChangeText={setName}/><Pressable style={s.check} onPress={()=>setAccepted(!accepted)}><Text>{accepted?'☑':'☐'} Customer approves this quote and accepts the terms.</Text></Pressable><Pressable style={[s.primary,!accepted&&s.disabled]} disabled={!accepted||name.trim().length<2} onPress={approve}><Text style={s.primaryText}>Approve quote</Text></Pressable></>}{!!msg&&<Text style={s.msg}>{msg}</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:'#f5f2ec'},center:{flex:1,alignItems:'center',justifyContent:'center'},pad:{padding:20,gap:12},top:{padding:20,flexDirection:'row',justifyContent:'space-between'},login:{flex:1,justifyContent:'center',padding:24,gap:12},brand:{fontSize:20,fontWeight:'700'},eyebrow:{fontSize:11,letterSpacing:2,color:'#746f66',marginTop:16},h1:{fontSize:34,fontWeight:'700',marginBottom:8},section:{fontSize:20,fontWeight:'700',marginTop:22},card:{backgroundColor:'#fff',padding:16,borderRadius:14,borderWidth:1,borderColor:'#e5e0d8',gap:5},cardTitle:{fontWeight:'700'},muted:{color:'#746f66',fontSize:12},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd6cc',borderRadius:10,padding:14},primary:{backgroundColor:'#171717',padding:15,borderRadius:10,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'700'},disabled:{opacity:.4},line:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:13,borderBottomWidth:1,borderBottomColor:'#ddd6cc'},grow:{flex:1},step:{flexDirection:'row',alignItems:'center',gap:12},stepText:{fontSize:25,paddingHorizontal:5},total:{flexDirection:'row',justifyContent:'space-between',paddingVertical:18},totalN:{fontSize:25,fontWeight:'700'},check:{paddingVertical:10},msg:{padding:12,backgroundColor:'#fff',borderRadius:10}});