const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}), headless: true });
  const context = await browser.newContext({ viewport: { width: 1715, height: 900 } });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const id = '00000000-0000-4000-8000-000000000001', org = '00000000-0000-4000-8000-000000000002';
  const user = { id, email: 'fixture@example.invalid', app_metadata: {}, user_metadata: {}, aud: 'authenticated', role: 'authenticated', created_at: new Date().toISOString() };
  const token = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url') + '.' + Buffer.from(JSON.stringify({ sub: id, aud: 'authenticated', exp: Math.floor(Date.now()/1000)+3600 })).toString('base64url') + '.fixture';
  const jobs = [], quotes = [], clients = [];
  const templates = ['Doors - Standard Replacement', 'Security Film - High Impact', 'Windows - Glass Replacement', 'Standard Patio Door Replacement + Lock', 'Locksmith - Emergency Re-key & Deadbolt'].map((name,i)=>({id:'template-'+i,name,trade:i===4?'Locksmith':i===1?'Security Film':i===2?'Windows':'Doors',description:'Fixture scope'}));
  const send = (route,data,status=200) => route.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-expose-headers':'content-range','content-range':'0-100/100'},body:JSON.stringify(data)});
  await page.route('https://jgbciyogyratfplofizv.supabase.co/**', async route => {
    const u=new URL(route.request().url()),body=route.request().postDataJSON?.()||{};
    if(route.request().method()==='OPTIONS') return send(route,{});
    if(u.pathname.endsWith('/auth/v1/token')) return send(route,{access_token:token,refresh_token:'fixture',expires_in:3600,token_type:'bearer',user});
    if(u.pathname.endsWith('/auth/v1/user')) return send(route,user);
    const table=u.pathname.split('/').pop();
    if(table==='organization_members') return send(route,u.search.includes('user_id')?{organization_id:org,user_id:id,role:'owner',active:true}:[{organization_id:org,user_id:id,role:'owner',active:true}]);
    if(table==='create_clarifi_request'){ const client={id:'client-1',...body.client_info,relationship:body.client_info.role};clients.push(client);jobs.push({id:'job-1',created_by:id,clients:client,client_id:client.id,request:body.job_info.title,details:body.job_info.details,service:body.job_info.service,request_markdown:body.job_info.markdown,status:'lead'});return send(route,'job-1'); }
    if(table==='save_clarifi_estimate'){const lines=body.lines,total=lines.reduce((sum,l)=>sum+l.price*l.quantity,0);quotes.push({id:'quote-1',job_id:'job-1',status:'draft',quote_number:'FIXTURE-1',client_message:body.scope_text,quote_versions:[{version_number:1,scope_markdown:body.scope_text,subtotal:total,tax:total*.13,total:total*1.13}]});return send(route,'quote-1');}
    if(u.pathname.includes('/rpc/')) return send(route,null);
    return send(route,({clients,jobs,quotes,scope_templates:templates})[table]||[]);
  });
  await page.route('**/api/assistant',async route=>{const b=route.request().postDataJSON();if(b.action==='request')return send(route,{client:{name:'Fixture Client',role:'owner',phone:'416-555-0123',email:'',address:'Toronto'},title:'Residential lock change',details:'Replace loose gripset',service:'Locksmith',markdown:'# Residential lock change\n\nReplace loose gripset.\n\n## Assignment\nUnassigned',technician_id:null,latitude:null,longitude:null,assignment_reason:'Unassigned'});return send(route,{scope:'# Lock replacement\n\nInstall matte black gripset.',lines:[{name:'Installation',quantity:1,unit:'hour',cost:null,price:null}],products:[{name:'Fixture gripset',supplier:'Home Depot Canada',cost:100,url:'https://www.homedepot.ca/product/fixture',image:null,evidence:'Fixture only',checked_at:new Date().toISOString()}],notes:'Confirm labour',template_name:'Locksmith'});});
  await page.goto('http://127.0.0.1:3000');
  await page.getByRole('button',{name:'Dispatch',exact:true}).click();
  await page.getByRole('textbox',{name:'Email address'}).fill('fixture@example.invalid');
  await page.getByRole('textbox',{name:'Password'}).fill('fixture-password');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('heading',{name:'Turn the call into the job.'}).waitFor();
  await page.screenshot({path:'verification-requests.png'});
  await page.keyboard.press('Alt+2');
  await page.getByRole('heading',{name:'Who is where.'}).waitFor();
  await page.screenshot({path:'verification-dispatch.png'});
  await page.keyboard.press('Alt+3');
  await page.getByRole('heading',{name:'Ready to go, not locked in.'}).waitFor();
  await page.screenshot({path:'verification-estimates.png'});
  await page.keyboard.press('Alt+n');
  await page.getByRole('textbox',{name:'Client call'}).fill('Fixture Client residential lock change');
  await page.getByRole('button',{name:'New request ↗',exact:true}).click();
  await page.getByRole('button',{name:'Save as new request'}).click();
  await page.getByRole('heading',{name:'Fixture Client',exact:true}).waitFor();
  assert.equal(jobs.length,1);
  await page.keyboard.press('Alt+e');
  await page.getByRole('textbox',{name:'Technician diagnosis'}).fill('Matte black gripset');
  await page.getByRole('button',{name:'New estimate ↗',exact:true}).click();
  await page.getByRole('button',{name:'Use this option'}).click();
  await page.getByRole('spinbutton',{name:'Client price (CAD)',exact:true}).first().fill('120');
  await page.getByRole('button',{name:'Client preview',exact:true}).click();
  const preview=page.locator('.estimate-preview');
  assert(!(await preview.innerText()).includes('Cost (internal)'));
  assert(!(await preview.innerText()).includes('Home Depot Canada'));
  await page.getByRole('button',{name:'Save as new estimate'}).click();
  await page.getByRole('heading',{name:'Ready to go, not locked in.'}).waitFor();
  assert.equal(quotes.length,1);
  await page.setViewportSize({width:390,height:844});
  await page.keyboard.press('Alt+n');
  await page.getByRole('textbox',{name:'Client call'}).waitFor();
  assert(await page.locator('dialog').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
  await page.screenshot({path:'verification-mobile.png'});
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Browser smoke passed: navigation, shortcuts, request save, estimate edit/save, customer cost hiding, mobile dialog. Synthetic data only.');
})().catch(e=>{console.error(e.message);process.exit(1)});
