'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib_supabase';
export default function CustomerQuote({params}:{params:{token:string}}){
 const token=params.token,[q,setQ]=useState<any>(null),[name,setName]=useState(''),[accepted,setAccepted]=useState(false),[change,setChange]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data,error}=await supabase.rpc('customer_quote',{raw_token:token});setQ(error?{valid:false}:data);if(data?.customer_name)setName(data.customer_name)})()},[token]);
 async function approve(){const {data,error}=await supabase.rpc('customer_approve_quote',{raw_token:token,typed_name:name,accepted});if(error||!data?.ok)return setMessage('Unable to approve this estimate. Check the required fields or link expiry.');setMessage(data.deposit_amount>0?'Approved. Deposit due: $'+Number(data.deposit_amount).toFixed(2)+'. Payment will be available when online payments are enabled.':'Estimate approved. Thank you.');setQ({...q,status:'approved'})}
 async function requestChange(){if(!change.trim())return setMessage('Please describe the requested change.');const {data}=await supabase.rpc('customer_request_quote_change',{raw_token:token,request_text:change});setMessage(data?'Your change request has been sent.':'Unable to submit this request.');if(data)setQ({...q,status:'changes_requested'})}
 if(!q)return <main className="customer-quote"><p>Loading estimate…</p></main>;
 if(!q.valid)return <main className="customer-quote"><section className="quote-sheet"><h1>This estimate link is unavailable.</h1><p>It may have expired or been replaced. Contact the company for a new link.</p></section></main>;
 return <main className="customer-quote"><section className="quote-sheet"><header><span className="eyebrow">{q.organization_name}</span><h1>Estimate {q.quote_number}</h1><p>{q.request}</p><small>{q.address}</small></header>{q.client_message&&<div className="quote-note">{q.client_message}</div>}<div className="quote-lines">{q.lines?.map((l:any,i:number)=><div className="quote-line" key={i}><div><strong>{l.name}</strong>{l.description&&<small>{l.description}</small>}{l.allowance&&<small>Allowance</small>}</div><span>{'$'}{Number(l.total).toFixed(2)}</span></div>)}</div><div className="quote-totals"><span>Subtotal <b>{'$'}{Number(q.subtotal).toFixed(2)}</b></span><span>Tax <b>{'$'}{Number(q.tax).toFixed(2)}</b></span><span className="grand">Total <b>{'$'}{Number(q.total).toFixed(2)}</b></span>{Number(q.deposit_percent)>0&&<span>Deposit on approval <b>{q.deposit_percent}%</b></span>}</div>{q.terms&&<details><summary>Terms</summary><p>{q.terms}</p></details>}{q.status==='approved'?<div className="success">Estimate approved.</div>:q.status==='changes_requested'?<div className="quote-note">Changes requested. The office will send an updated estimate.</div>:<><div className="approval"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I approve this estimate and accept the terms.</label><button className="primary" disabled={!accepted||name.trim().length<2} onClick={approve}>Approve estimate</button></div><details className="changes"><summary>Request changes</summary><textarea value={change} onChange={e=>setChange(e.target.value)} placeholder="Tell us what you would like changed."/><button className="secondary" onClick={requestChange}>Send request</button></details></>}{message&&<p className="notice">{message}</p>}<footer>Questions? {q.reply_to}</footer></section></main>
}