'use client';

import { useEffect, useState } from 'react';
import { supabase } from './lib_supabase';
import dynamic from 'next/dynamic';
const DispatchMap = dynamic(() => import('./DispatchMap'), { ssr: false, loading: () => <p role="status">Loading map…</p> });

type View = 'today'|'dashboard'|'clients'|'leads'|'jobs'|'schedule'|'dispatch'|'estimates'|'measurements'|'photos'|'templates'|'invoices'|'team';
const statusClass:Record<string,string>={lead:'lead',active:'active',estimate:'estimate',completed:'completed'};

export default function Home(){
 const [mode,setMode]=useState<'field'|'office'>('field');
 const [session,setSession]=useState<any>(null),[view,setView]=useState<View>('today'),[loading,setLoading]=useState(true);
 const [clients,setClients]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]),[measurements,setMeasurements]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[techs,setTechs]=useState<any[]>([]),[requirements,setRequirements]=useState<any[]>([]),[files,setFiles]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[selectedProfile,setSelectedProfile]=useState(''),[autoEstimate,setAutoEstimate]=useState<any>(null);
 const [orgId,setOrgId]=useState(''),[showIntake,setShowIntake]=useState(false),[clientType,setClientType]=useState('Tenant'),[authEmail,setAuthEmail]=useState(''),[authPassword,setAuthPassword]=useState(''),[authMessage,setAuthMessage]=useState('');
 const [fieldQuote,setFieldQuote]=useState<any>(null),[fieldCatalog,setFieldCatalog]=useState<any[]>([]),[fieldSearch,setFieldSearch]=useState(''),[fieldName,setFieldName]=useState(''),[fieldAccepted,setFieldAccepted]=useState(false),[selectedJob,setSelectedJob]=useState(''),[itemName,setItemName]=useState('Labour & materials'),[qty,setQty]=useState('1'),[unitPrice,setUnitPrice]=useState('0'),[taxRate,setTaxRate]=useState('13'),[notice,setNotice]=useState('');

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadData();else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadData();else {setLoading(false);setJobs([]);setFieldQuote(null)}});return()=>subscription.unsubscribe()},[]);
 async function membership(){const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data}=await supabase.from('organization_members').select('organization_id,role').eq('user_id',user.id).limit(1).maybeSingle();return data}
 async function loadData(){setLoading(true);const m=await membership();if(!m){setLoading(false);return}setOrgId(m.organization_id);const [c,j,q,i,t,me,mb,te,rq,fi,mp,su]=await Promise.all([
  supabase.from('clients').select('*').order('created_at',{ascending:false}),supabase.from('jobs').select('*,clients(*)').order('created_at',{ascending:false}),supabase.from('quotes').select('*').order('created_at',{ascending:false}),supabase.from('invoices').select('*').order('created_at',{ascending:false}),supabase.from('scope_templates').select('*').order('name'),supabase.from('job_measurements').select('*').order('created_at',{ascending:false}),supabase.from('organization_members').select('*').order('created_at'),supabase.from('technicians').select('*').eq('active',true).order('name'),supabase.from('job_requirements').select('*').order('created_at'),supabase.from('job_files').select('*').order('created_at',{ascending:false}),supabase.from('markup_profiles').select('*').eq('active',true).order('name'),supabase.from('suppliers').select('*').eq('active',true).order('name')
 ]);setClients(c.data||[]);setJobs(j.data||[]);setQuotes(q.data||[]);setInvoices(i.data||[]);setTemplates(t.data||[]);setMeasurements(me.data||[]);setMembers(mb.data||[]);setTechs(te.data||[]);setRequirements(rq.data||[]);setFiles(fi.data||[]);setProfiles(mp.data||[]);setSuppliers(su.data||[]);setLoading(false)}
 async function authenticate(){setAuthMessage('');const r=await supabase.auth.signInWithPassword({email:authEmail,password:authPassword});if(r.error)setAuthMessage(r.error.message)}
 async function createLead(){const m=await membership();if(!m)return alert('No Clarifi workspace assigned.');const q=(s:string)=>(document.querySelector(s) as HTMLInputElement)?.value||'';const rel=clientType.toLowerCase().replaceAll(' ','_');const {data:client,error}=await supabase.from('clients').insert({organization_id:m.organization_id,name:q('#client-name'),email:q('#client-email')||null,phone:q('#client-phone')||null,address:q('#client-address')||null,relationship:rel}).select().single();if(error)return alert(error.message);const {error:je}=await supabase.from('jobs').insert({organization_id:m.organization_id,client_id:client.id,request:q('#client-request')||'General service request',details:q('#client-details')||null,status:'lead'});if(je)return alert(je.message);setShowIntake(false);await loadData()}
 async function updateJob(id:string,patch:any){const {error}=await supabase.from('jobs').update({...patch,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await loadData()}
 async function refreshFieldQuote(jobId=selectedJob){if(!jobId)return;const {data,error}=await supabase.rpc('calculate_field_quote',{target_job:jobId,selected_profile:null});if(error)return setNotice(error.message);setFieldQuote(data)}
 async function startFieldQuote(templateId:string){if(!selectedJob)return setNotice('Select a job first.');const {error}=await supabase.rpc('start_field_quote',{target_job:selectedJob,target_template:templateId});if(error)return setNotice(error.message);setNotice('Template loaded. Adjust only what changed on site.');await refreshFieldQuote(selectedJob)}
 async function changeFieldQty(item:any,delta:number){const current=item.type==='labour'?Number(item.quantity||1):Number(item.quantity||0);const next=Math.max(0,current+delta);const {error}=await supabase.rpc('update_field_quote_quantity',{target_item:item.id,new_quantity:next});if(error)return setNotice(error.message);await refreshFieldQuote()}
 async function searchFieldCatalog(){if(!selectedJob)return;const {data,error}=await supabase.rpc('field_quote_catalog',{target_job:selectedJob,search_text:fieldSearch});if(error)return setNotice(error.message);setFieldCatalog(data||[])}
 async function addFieldMaterial(productId:string){const {error}=await supabase.rpc('add_field_quote_material',{target_job:selectedJob,target_product:productId,qty:1});if(error)return setNotice(error.message);setFieldCatalog([]);setFieldSearch('');await refreshFieldQuote()}
 async function approveFieldQuote(){if(!fieldAccepted||fieldName.trim().length<2)return setNotice('Customer full name and approval are required.');const {data,error}=await supabase.rpc('finalize_field_quote',{target_job:selectedJob,typed_name:fieldName,accepted:true});if(error)return setNotice(error.message);setNotice('Approved. Quote locked and invoice outline created.');setFieldQuote(null);setFieldAccepted(false);await loadData()}
 async function calculateAutoEstimate(){if(!selectedJob)return setNotice('Select a job first.');const {data,error}=await supabase.rpc('calculate_estimate',{target_job:selectedJob,selected_profile:selectedProfile||null});if(error){setAutoEstimate(null);return setNotice(error.message)}setAutoEstimate(data);setNotice(data.margin_ok?'Ready for office review.':'Margin below template minimum — office override/review required.')}
 async function finalizeAutoEstimate(){if(!selectedJob)return setNotice('Select a job first.');const {data,error}=await supabase.rpc('finalize_scope_estimate',{target_job:selectedJob,selected_profile:selectedProfile||null});if(error)return setNotice(error.message);setAutoEstimate(null);setNotice('Draft estimate created from scope.');await loadData()}
 async function setQuoteTerms(q:any){const expiry=Number(window.prompt('Quote valid for how many days?',String(q.expiry_days||14)));if(!expiry)return;const dep=window.prompt('Deposit % (blank = template/profile default)',q.deposit_override_percent==null?'':String(q.deposit_override_percent));const {error}=await supabase.rpc('set_quote_commercial_terms',{target_quote:q.id,expiry,deposit_pct:dep===''?null:Number(dep)});if(error)return setNotice(error.message);setNotice('Estimate terms updated.');await loadData()}
 async function completeServiceCall(jobId:string){const {error}=await supabase.rpc('mark_service_call_complete',{target_job:jobId});if(error)return setNotice(error.message);setNotice('Service call completed. Appointment may now be confirmed.');await loadData()}
 async function sendEstimate(q:any){const job=jobs.find(j=>j.id===q.job_id),email=job?.clients?.email;if(!email)return setNotice('Client email is required before sending.');const {error}=await supabase.rpc('mark_quote_sent',{target_quote:q.id,channel:'email',recipient:email});if(error)return setNotice(error.message);setNotice('Estimate queued for email provider.');await loadData()}
 async function createInvoiceFromQuote(q:any){const {error}=await supabase.rpc('create_invoice_from_approved_quote',{target_quote:q.id});if(error)return setNotice(error.message);setNotice('Invoice created from approved estimate.');await loadData()}
 async function requestChanges(q:any){const reason=window.prompt('What needs to change?');if(!reason)return;const {error}=await supabase.rpc('request_quote_change',{target_quote:q.id,request_text:reason});if(error)return setNotice(error.message);setNotice('Change request recorded.');await loadData()}
 async function recordApproval(q:any){const job=jobs.find(j=>j.id===q.job_id),name=job?.clients?.name||'Customer',email=job?.clients?.email||null;const {error}=await supabase.rpc('record_quote_approval',{target_quote:q.id,approver_name:name,approver_email:email});if(error)return setNotice(error.message);setNotice('Approval recorded. Job activated.');await loadData()}
 async function createEstimate(){if(!selectedJob)return setNotice('Select a job first.');const pending=requirements.filter(r=>r.job_id===selectedJob&&r.required&&!r.completed);if(pending.length)return setNotice(`Not ready: ${pending.length} required scope/photo items are incomplete.`);const job=jobs.find(x=>x.id===selectedJob);const subtotal=Number(qty)*Number(unitPrice),tax=subtotal*(Number(taxRate)/100),total=subtotal+tax;const num='Q-'+Date.now().toString().slice(-7);const {data:qrow,error}=await supabase.from('quotes').insert({organization_id:orgId,job_id:selectedJob,quote_number:num,status:'draft'}).select().single();if(error)return setNotice(error.message);const {data:v,error:ve}=await supabase.from('quote_versions').insert({quote_id:qrow.id,version_number:1,subtotal,tax,total,created_by:session.user.id}).select().single();if(ve)return setNotice(ve.message);const {error:le}=await supabase.from('quote_line_items').insert({quote_version_id:v.id,item_name:itemName,quantity:Number(qty),unit:'each',unit_cost:Number(unitPrice),markup_percent:0,unit_price:Number(unitPrice),total:subtotal});if(le)return setNotice(le.message);await updateJob(selectedJob,{status:'estimate'});setNotice(`${num} created for ${job?.clients?.name||'client'}.`);await loadData()}
 async function approveEstimate(id:string,jobId:string){const {error}=await supabase.from('quotes').update({status:'approved',approved_at:new Date().toISOString(),approved_by:session.user.id}).eq('id',id);if(error)return alert(error.message);await updateJob(jobId,{status:'active'});await loadData()}
 async function addMeasurement(){if(!selectedJob)return setNotice('Select a job first.');const label=(document.querySelector('#measure-label') as HTMLInputElement)?.value||'';const value=(document.querySelector('#measure-value') as HTMLInputElement)?.value||'';const unit=(document.querySelector('#measure-unit') as HTMLInputElement)?.value||'';if(!label)return setNotice('Measurement label is required.');const {error}=await supabase.from('job_measurements').insert({organization_id:orgId,job_id:selectedJob,label,value:value?Number(value):null,unit:unit||null,created_by:session.user.id});if(error)return setNotice(error.message);setNotice('Measurement saved.');await loadData()}
 async function assignTech(jobId:string,technician_id:string){await updateJob(jobId,{technician_id:technician_id||null})}
 async function toggleRequirement(id:string,completed:boolean){const {error}=await supabase.from('job_requirements').update({completed}).eq('id',id);if(error)return alert(error.message);await loadData()}
 async function uploadJobPhoto(jobId:string,file:File){const path=`${jobId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('job-files').upload(path,file);if(up.error)return alert(up.error.message);const {error}=await supabase.from('job_files').insert({organization_id:orgId,job_id:jobId,storage_path:path,file_name:file.name,mime_type:file.type});if(error)return alert(error.message);await loadData()}
 const jobName=(id:string)=>{const j=jobs.find(x=>x.id===id);return j?`${j.clients?.name||'Client'} — ${j.request}`:'Job'};
 if(!session)return <main className="auth-shell"><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark">C</span><span>clarifi</span></div><p className="eyebrow">PRIVATE WORKSPACE</p><h1>Welcome back.</h1><p className="auth-copy">Staff-only service operations.</p><label>Email<input autoComplete="username" type="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)}/></label><label>Password<input autoComplete="current-password" type="password" value={authPassword} onChange={e=>setAuthPassword(e.target.value)}/></label>{authMessage&&<p className="auth-message">{authMessage}</p>}<button className="primary wide" onClick={authenticate}>Sign in</button><p className="auth-message">Accounts are provisioned by Clarifi administration.</p></div></main>;

 const nav = <nav className="app-nav" aria-label="Office navigation">{(['dashboard','clients','leads','jobs','schedule','dispatch','estimates','measurements','photos','templates','invoices','team'] as View[]).map(v=><button key={v} className={view===v?'nav-active':''} onClick={()=>setView(v)}>{v==='measurements'?'Scope':v[0].toUpperCase()+v.slice(1)}</button>)}</nav>;
 return <main className={`shell ${mode}-mode`}><header className="topbar"><button className="brand" onClick={()=>setView(mode==='field'?'today':'dashboard')}><span className="brand-mark">C</span><span>clarifi</span></button><div className="top-actions"><div className="mode-switch" aria-label="Workspace mode"><button aria-pressed={mode==='field'} onClick={()=>{setMode('field');setView('today')}}>Field</button><button aria-pressed={mode==='office'} onClick={()=>{setMode('office');setView('dashboard')}}>Office</button></div><button aria-label="Sign out" title="Sign out" className="avatar" onClick={()=>supabase.auth.signOut()}>A</button></div></header>{mode==='office'?nav:<nav className="field-nav" aria-label="Field navigation">{([['today','Today'],['templates','Quote'],['measurements','Scope'],['photos','Photos']] as [View,string][]).map(([v,label])=><button key={v} aria-current={view===v?'page':undefined} className={view===v?'nav-active':''} onClick={()=>setView(v)}>{label}</button>)}</nav>}
 <section className="view admin-view" aria-busy={loading}>
 {loading&&<p role="status">Loading workspace…</p>}
 {notice&&view!=='templates'&&<p className="auth-message" role="status">{notice}</p>}
 {view==='today'&&<><div className="view-heading"><div><p className="eyebrow">FIELD WORKSPACE</p><h1>Today’s work</h1></div><button className="primary" onClick={()=>setShowIntake(true)}>+ New request</button></div><div className="field-job-list">{jobs.filter(j=>j.status!=='completed').sort((a,b)=>(a.scheduled_start||'9999').localeCompare(b.scheduled_start||'9999')).map(j=><article className="field-job-card" key={j.id}><div className="field-job-meta"><span className={'pill '+(statusClass[j.status]||'lead')}>{j.status}</span><span>{j.scheduled_start?new Date(j.scheduled_start).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Unscheduled'}</span></div><h2>{j.clients?.name||'Client'}</h2><p>{j.request}</p>{j.clients?.address&&<p className="job-address">{j.clients.address}</p>}<div className="button-wrap"><button className="primary" onClick={()=>{setSelectedJob(j.id);setFieldQuote(null);setFieldCatalog([]);setFieldName('');setFieldAccepted(false);setNotice('');setView('templates');refreshFieldQuote(j.id)}}>Open quote</button><button className="secondary" onClick={()=>{setSelectedJob(j.id);setView('measurements')}}>Scope</button><button className="secondary" onClick={()=>{setSelectedJob(j.id);setView('photos')}}>Photos</button>{j.service_call_required&&!j.service_call_completed_at&&<button className="secondary" onClick={()=>completeServiceCall(j.id)}>Complete service call</button>}{j.status==='active'&&<button className="secondary" onClick={()=>updateJob(j.id,{status:'completed'})}>Complete job</button>}</div></article>)}{!loading&&!jobs.some(j=>j.status!=='completed')&&<div className="empty">No open jobs. Create a request to start.</div>}</div></>}

  {view==='dashboard'&&<><div className="view-heading"><div><p className="eyebrow">ADMIN DASHBOARD</p><h1>Operations</h1></div><button className="primary" onClick={()=>setShowIntake(true)}>+ New client / request</button></div><div className="stat-grid"><Stat n={jobs.filter(j=>j.status==='lead').length} label="New leads"/><Stat n={requirements.filter(r=>r.required&&!r.completed).length} label="Scope items due"/><Stat n={quotes.filter(q=>q.status==='draft').length} label="Quotes to review"/><Stat n={quotes.filter(q=>q.status==='sent').length} label="Awaiting approval"/><Stat n={jobs.filter(j=>j.status==='active').length} label="Active jobs"/></div><div className="workflow-strip"><span>Intake</span><b>→</b><span>Scope</span><b>→</b><span>Price</span><b>→</b><span>Send</span><b>→</b><span>Approve</span><b>→</b><span>Dispatch</span></div><h2 className="subhead">Recent work</h2><JobTable jobs={jobs.slice(0,8)} updateJob={updateJob}/></>}
  {view==='clients'&&<><Head title="Clients" action={()=>setShowIntake(true)}/><div className="client-table"><div className="table-head"><span>Client</span><span>Type</span><span>Contact</span><span>Location</span></div>{clients.map(c=><div className="table-row" key={c.id}><div><strong>{c.name}</strong><small>{jobs.filter(j=>j.client_id===c.id).length} requests</small></div><span>{c.relationship.replaceAll('_',' ')}</span><span>{c.phone||c.email||'—'}</span><span>{c.address||'—'}</span></div>)}</div></>}
  {view==='leads'&&<><Head title="Leads"/><JobTable jobs={jobs.filter(j=>j.status==='lead')} updateJob={updateJob}/></>}
  {view==='jobs'&&<><Head title="Jobs"/><JobTable jobs={jobs.filter(j=>j.status!=='lead')} updateJob={updateJob}/></>}
  {view==='schedule'&&<><Head title="Schedule & dispatch"/><div className="client-table"><div className="table-head"><span>Job</span><span>Status</span><span>Start</span><span>Actions</span></div>{jobs.map(j=><div className="table-row" key={j.id}><div><strong>{j.clients?.name}</strong><small>{j.request}</small></div><span className={'pill '+(statusClass[j.status]||'lead')}>{j.status}</span>{j.service_call_required&&!j.service_call_completed_at&&<button className="secondary compact" onClick={()=>completeServiceCall(j.id)}>Complete service call</button>}<input className="inline-input" type="datetime-local" defaultValue={j.scheduled_start?new Date(j.scheduled_start).toISOString().slice(0,16):''} onBlur={e=>e.target.value&&updateJob(j.id,{scheduled_start:new Date(e.target.value).toISOString()})}/><select className="inline-input" value={j.technician_id||''} onChange={e=>assignTech(j.id,e.target.value)}><option value="">Unassigned</option>{techs.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>)}</div></>}
  {view==='dispatch'&&<><Head title="Dispatch map"/><div className="work-card"><h3>Location-aware dispatch</h3><p>Account-free MVP map powered by OpenStreetMap. Jobs appear once their coordinates are saved.</p><DispatchMap jobs={jobs}/><div className="button-wrap"><span className="pill active">Today</span><span className="pill lead">Unassigned</span><span className="pill estimate">Needs pickup</span></div></div><div className="module-grid"><div className="module"><span className="eyebrow">OPENSTREETMAP</span><h3>Live MVP map</h3><p>No developer account required. Leaflet renders client/job markers with required OSM attribution.</p></div><div className="module"><span className="eyebrow">ROUTING UPGRADE</span><h3>Traffic + optimization</h3><p>Google/MapQuest adapters remain available later when credentials are configured.</p></div><div className="module"><span className="eyebrow">SUPPLIERS</span><h3>{suppliers.length} active</h3><p>{suppliers.map(s=>s.name).join(', ')||'No suppliers configured'}</p></div></div></>}
  {view==='estimates'&&<><Head title="Estimates"/><div className="work-card"><h3>Create estimate</h3><div className="form-row"><select className="inline-input" value={selectedProfile} onChange={e=>setSelectedProfile(e.target.value)}><option value="">Template pricing profile</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.material_markup_percent}% materials</option>)}</select><span className="pill active">13% Ontario HST default</span></div><select aria-label="Select job" value={selectedJob} onChange={e=>setSelectedJob(e.target.value)}><option value="">Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{jobName(j.id)}</option>)}</select><div className="form-row"><button className="primary" onClick={calculateAutoEstimate}>Calculate from scope</button>{autoEstimate&&<><span className="pill active">Subtotal ${Number(autoEstimate.subtotal).toFixed(2)}</span><span className="pill estimate">Margin {autoEstimate.margin_percent}%</span><span className="pill active">Total ${Number(autoEstimate.total).toFixed(2)}</span><button className="primary" onClick={finalizeAutoEstimate}>Create estimate</button></>}</div><div className="form-row"><input value={itemName} onChange={e=>setItemName(e.target.value)} placeholder="Line item"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" placeholder="Qty"/><input value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} type="number" placeholder="Unit price"/><input value={taxRate} onChange={e=>setTaxRate(e.target.value)} type="number" placeholder="Tax %"/><button className="primary" onClick={createEstimate}>Create draft</button></div>{autoEstimate&&<div className="estimate-preview">{autoEstimate.lines?.map((l:any,i:number)=><div key={i}><span>{l.item_name}</span><span>{l.quantity} {l.unit}</span><strong>${Number(l.total).toFixed(2)}</strong></div>)}</div>}{notice&&<p className="auth-message">{notice}</p>}</div><div className="client-table"><div className="table-head"><span>Estimate</span><span>Job</span><span>Status</span><span>Action</span></div>{quotes.map(q=><div className="table-row" key={q.id}><strong>{q.quote_number}</strong><span>{jobName(q.job_id)}</span><span className="pill estimate">{q.status}{q.sent_at?' · sent':''}{q.viewed_at?' · viewed':''}</span>{q.status==='approved'?<><span>Approved · job active</span><button className="secondary compact" onClick={()=>createInvoiceFromQuote(q)}>Create invoice</button></>:q.status==='sent'?<><button className="primary compact" onClick={()=>recordApproval(q)}>Record approval</button><button className="secondary compact" onClick={()=>requestChanges(q)}>Changes</button></>:q.status==='changes_requested'?<span>Changes requested</span>:<><button className="secondary compact" onClick={()=>setQuoteTerms(q)}>Terms</button><button className="secondary compact" onClick={()=>sendEstimate(q)}>Send email</button></>}</div>)}</div></>}
  {view==='measurements'&&<><Head title="Scope & measurements"/><div className="work-card"><select aria-label="Select job" value={selectedJob} onChange={e=>setSelectedJob(e.target.value)}><option value="">Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{jobName(j.id)}</option>)}</select><div className="form-row"><input id="measure-label" placeholder="Width / Height / Glass type"/><input id="measure-value" type="number" placeholder="Value"/><input id="measure-unit" placeholder="in / ft / mm"/><button className="primary" onClick={addMeasurement}>Save measurement</button></div>{notice&&<p className="auth-message">{notice}</p>}</div><div className="client-table"><div className="table-head"><span>Job</span><span>Measurement</span><span>Value</span><span>Notes</span></div>{measurements.map(m=><div className="table-row" key={m.id}><span>{jobName(m.job_id)}</span><strong>{m.label}</strong><span>{m.value??'—'} {m.unit||''}</span><span>{m.notes||'—'}</span></div>)}</div></>}
  {view==='photos'&&<><Head title="Photos & readiness"/><div className="client-table"><div className="table-head"><span>Job</span><span>Required checklist</span><span>Photos</span><span>Upload</span></div>{jobs.filter(j=>mode==='office'||!selectedJob||j.id===selectedJob).map(j=>{const req=requirements.filter(r=>r.job_id===j.id),pending=req.filter(r=>r.required&&!r.completed),jf=files.filter(f=>f.job_id===j.id);return <div className="table-row readiness-row" key={j.id}><div><strong>{j.clients?.name}</strong><small>{j.request}</small><small>{pending.length?`${pending.length} required items remaining`:'Estimate ready'}</small></div><div>{req.map(r=><label className="check" key={r.id}><input type="checkbox" checked={r.completed} onChange={e=>toggleRequirement(r.id,e.target.checked)}/>{r.label}</label>)}</div><span>{jf.length} uploaded</span><label className="secondary compact upload-button">+ Photo<input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&uploadJobPhoto(j.id,e.target.files[0])}/></label></div>})}</div></>}
  {view==='templates'&&<><Head title="Field quote"/><div className="field-quote"><div className="field-quote-top"><div><span className="eyebrow">30-SECOND FIELD QUOTE</span><h2>Build quote on site</h2></div><select aria-label="Select job" value={selectedJob} onChange={e=>{setSelectedJob(e.target.value);setFieldQuote(null);setFieldCatalog([]);setFieldName('');setFieldAccepted(false);setNotice('');refreshFieldQuote(e.target.value)}}><option value="">Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{jobName(j.id)}</option>)}</select></div>{!selectedJob&&<p className="empty">Select a job to open its quote or choose a template.</p>}{selectedJob&&!fieldQuote&&<div className="template-picks">{templates.map(t=><button className="template-pick" key={t.id} onClick={()=>startFieldQuote(t.id)}><small>{t.trade}</small><strong>{t.name}</strong><span>{t.description}</span></button>)}</div>}{fieldQuote&&<><div className="field-items">{fieldQuote.lines?.map((x:any)=><div className="field-item" key={x.id}><div><strong>{x.name}</strong><small>{x.type==='labour'?'Labour hours':x.unit}</small></div><div className="qty-control"><button aria-label={`Decrease ${x.name} quantity`} onClick={()=>changeFieldQty(x,-1)}>−</button><b>{Number(x.quantity)}</b><button aria-label={`Increase ${x.name} quantity`} onClick={()=>changeFieldQty(x,1)}>+</button></div><span>$ {Number(x.sell_total).toFixed(2)}</span></div>)}</div><div className="add-material"><input aria-label="Search material catalog" value={fieldSearch} onChange={e=>setFieldSearch(e.target.value)} placeholder="Search material catalog"/><button className="secondary compact" onClick={searchFieldCatalog}>Add material</button>{fieldCatalog.length>0&&<div className="catalog-results">{fieldCatalog.map(p=><button key={p.id} onClick={()=>addFieldMaterial(p.id)}><span>{p.name}</span><small>{p.source} · last verified {p.last_verified_at?new Date(p.last_verified_at).toLocaleDateString():'not verified'}</small></button>)}</div>}</div><div className="field-total"><span>Subtotal <b>$ {Number(fieldQuote.subtotal).toFixed(2)}</b></span><span>Tax <b>$ {Number(fieldQuote.tax).toFixed(2)}</b></span><span className="grand">Total <b>$ {Number(fieldQuote.total).toFixed(2)}</b></span></div><div className="field-approval"><input aria-label="Customer full name" placeholder="Customer full name" value={fieldName} onChange={e=>setFieldName(e.target.value)}/><label className="check"><input type="checkbox" checked={fieldAccepted} onChange={e=>setFieldAccepted(e.target.checked)}/> Customer approves this quote and accepts the terms.</label><button className="primary" disabled={!fieldAccepted||fieldName.trim().length<2} onClick={approveFieldQuote}>Approve quote</button></div></>}{notice&&<p className="auth-message">{notice}</p>}</div><div className="module-grid template-library">{templates.map(t=><div className="module" key={t.id}><span className="eyebrow">{t.trade}</span><h3>{t.name}</h3><p>{t.description}</p></div>)}</div></>}
  {view==='invoices'&&<><Head title="Invoices"/><div className="client-table"><div className="table-head"><span>Invoice</span><span>Job</span><span>Status</span><span>Total</span></div>{invoices.map(i=><div className="table-row" key={i.id}><strong>{i.invoice_number}</strong><span>{jobName(i.job_id)}</span><span className="pill active">{i.status}</span><span>${Number(i.total).toFixed(2)}</span></div>)}</div></>}
  {view==='team'&&<><Head title="Team & settings"/><div className="module-grid"><div className="module"><span className="eyebrow">WORKSPACE</span><h3>Clarifi Workspace</h3><p>{members.length} staff account{members.length===1?'':'s'} · {techs.length} technician profile{techs.length===1?'':'s'}.</p></div><div className="module"><span className="eyebrow">SECURITY</span><h3>Internal only</h3><p>No public signup, anonymous customer portal or public quote approval.</p></div></div></>}
 </section>
 {showIntake&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowIntake(false)}}><div className="modal"><div className="modal-top"><div><p className="eyebrow">NEW REQUEST</p><h2>Start with the client.</h2></div><button className="close" onClick={()=>setShowIntake(false)}>×</button></div><div className="form-grid"><label>Client name<input id="client-name" placeholder="Full name or company"/></label><label>Email<input id="client-email" type="email"/></label><label>Phone<input id="client-phone"/></label><label>Property address<input id="client-address"/></label><label>Relationship<select value={clientType} onChange={e=>setClientType(e.target.value)}><option>Tenant</option><option>Landlord</option><option>Property Management</option><option>Commercial</option><option>Other</option></select></label><label>Request<input id="client-request"/></label></div><label className="full">Details<textarea id="client-details"/></label><div className="modal-actions"><button className="secondary" onClick={()=>setShowIntake(false)}>Cancel</button><button className="primary" onClick={createLead}>Create lead</button></div></div></div>}
 </main>
}

function Head({title,action}:{title:string,action?:()=>void}){return <div className="view-heading"><div><p className="eyebrow">CLARIFI MVP</p><h1>{title}</h1></div>{action&&<button className="primary" onClick={action}>+ New client / request</button>}</div>}
function Stat({n,label}:{n:number,label:string}){return <div className="stat"><strong>{n}</strong><span>{label}</span></div>}
function JobTable({jobs,updateJob}:{jobs:any[],updateJob:(id:string,p:any)=>void}){return <div className="client-table"><div className="table-head"><span>Client / request</span><span>Type</span><span>Status</span><span>Action</span></div>{jobs.length===0?<div className="empty">No records yet.</div>:jobs.map(j=><div className="table-row" key={j.id}><div><strong>{j.clients?.name||'Client'}</strong><small>{j.request}</small></div><span>{(j.clients?.relationship||'—').replaceAll('_',' ')}</span><span className={'pill '+(statusClass[j.status]||'lead')}>{j.status}</span><select className="inline-input" value={j.status} onChange={e=>updateJob(j.id,{status:e.target.value})}><option value="lead">Lead</option><option value="estimate">Estimate</option><option value="active">Active</option><option value="completed">Completed</option></select></div>)}</div>}
